version: '3.7'

services:
  database:
    container_name: database
    image: mongo
    ports: 
      - '27017:27017'
  congressional-members-search-api:
    container_name: congressional-members-search-api
    build:
      context: ./congressional-members-search-api
      dockerfile: Dockerfile
    depends_on:
        - database
    links:
        - database
    volumes:
        - '.:/app'
        - '/app/congressional-members-search-api/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  congressional-members-search-ui:
    container_name: congressional-members-search-ui
    build:
      context: ./congressional-members-search-ui
      dockerfile: Dockerfile
    depends_on:
        - congressional-members-search-api
    volumes:
      - '.:/app'
      - '/app/congressional-members-search-ui/node_modules'
    ports:
      - '80:8080'
    environment:
      - NODE_ENV=development



