version: '3.7'

services:
  database:
    container_name: database
    image: mongo
    ports: 
      - '27017:27017'
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
        - database
    links:
        - database
    volumes:
        - '.:/app'
        - '/app/api/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
        - api
    volumes:
      - '.:/app'
      - '/app/ui/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development



